---
plugin: gcp_compute
zones:
  - europe-west1-b
projects:
  - docker-326406
service_account_file: docker-326406.json
auth_kind: serviceaccount
scopes:
  - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/compute.readonly
keyed_groups:
  - key: labels.ansible_group
    separator: ''
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
